# Utiliza una imagen base de Python
FROM python:3.10-slim

RUN  apt-get update && apt-get install -y libmagic1

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de requerimientos a la imagen
COPY requirements.txt .

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copia el código de la aplicación a la imagen
COPY . .

RUN cp config_docker_pro.py config.py

# Expone el puerto en el que correrá la aplicación
EXPOSE 8000

# Comando para correr la aplicación usando Gunicorn
CMD ["gunicorn", "-w", "8", "-k", "uvicorn.workers.UvicornWorker", "main:app", "--bind", "0.0.0.0:8000"]
