# --- Identificación del Proyecto ---
sonar.projectKey=superWeb
sonar.projectName=superWeb
sonar.projectVersion=1.0

# --- Rutas de Código ---
sonar.sources=src
sonar.exclusions=**/node_modules/**, **/dist/**, **/tests/**, **/*.spec.js, **/venv/**

# --- Configuración para Vue.js / TypeScript / JS ---
# En versiones modernas de SonarQube, basta con asociar .vue al lenguaje JS
sonar.lang.patterns.js=**/*.js,**/*.jsx,**/*.vue
sonar.lang.patterns.ts=**/*.ts,**/*.tsx

# Importante para que analice el código dentro de los SFC de Vue
sonar.typescript.tsconfigPath=tsconfig.json

# --- Reportes Externos ---
sonar.eslint.reportPaths=eslint-report.json

# --- Cobertura ---
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# --- Codificación ---
sonar.sourceEncoding=UTF-8