
export const INVEST_STATUS_PENDING = 0
export const INVEST_STATUS_NEXT_LAUNCH = 1
export const INVEST_STATUS_FINANCING_PHASE = 2
export const INVEST_STATUS_IN_PROGRESS = 3
export const INVEST_STATUS_FINISHED = 99


export const USERS_INVEST_TYPE_BUY = 2
export const USERS_INVEST_TYPE_BUY_REJECTED = 3
export const USERS_INVEST_TYPE_SOLD = 16

export const USERS_INVEST_TYPE_PROFITS = 25
export const USERS_INVEST_TYPE_PROFITS_CLAIM = 26
export const USERS_INVEST_TYPE_PROFITS_RECEIVED = 27


export const USERS_INVEST_TYPE_DEPOSIT = 30  // tiene subtipos, puede ser deposito por añadir capital, referidos, final de proyecto etc
export const USERS_INVEST_TYPE_DEPOSIT_CLAIM = 31
export const USERS_INVEST_TYPE_DEPOSIT_RECEIVED = 32
export const USERS_INVEST_TYPE_DEPOSIT_TO_INVEST = 33


export const USERS_INVEST_TYPE_REFUND = 40
export const USERS_INVEST_TYPE_CLOSE_PROJECT_REFUND = 41
export const USERS_INVEST_TYPE_REFUND_PARTIAL = 42


///// SUBTIPOS DE DEPOSITOS DE ENTRADA DE DINERO PARA EL TIPO USERS_INVEST_TYPE_DEPOSIT
export const DEPOSIT_SUBTYPE_CLOSE_PROJECT = 0
export const DEPOSIT_SUBTYPE_ADD_BY_CRYPTO = 3
export const DEPOSIT_SUBTYPE_PROFITS = 4


export const FILE_TYPE_DNI_BACK = 2
export const FILE_TYPE_DNI_FRONT = 3
export const FILE_TYPE_DRIVE_LICENSE_BACK = 5
export const FILE_TYPE_DRIVE_LICENSE_FRONT = 6
export const FILE_TYPE_RESIDENCE_CARD_BACK = 7
export const FILE_TYPE_RESIDENCE_CARD_FRONT = 8
export const FILE_TYPE_PASSPORT_EU_BACK = 9
export const FILE_TYPE_PASSPORT_EU_FRONT = 10
export const FILE_TYPE_PASSPORT_OUTSIDE_EU_FRONT = 11

export const FILE_TYPE_LEGAL_PERSON_REPRESENTATIVE_DNI_BACK = 20
export const FILE_TYPE_LEGAL_PERSON_REPRESENTATIVE_DNI_FRONT = 21
export const FILE_TYPE_LEGAL_PERSON_REPRESENTATIVE_DRIVE_LICENSE_BACK = 22
export const FILE_TYPE_LEGAL_PERSON_REPRESENTATIVE_DRIVE_LICENSE_FRONT = 23
export const FILE_TYPE_LEGAL_PERSON_REPRESENTATIVE_RESIDENCE_CARD_BACK = 24
export const FILE_TYPE_LEGAL_PERSON_REPRESENTATIVE_RESIDENCE_CARD_FRONT = 25
export const FILE_TYPE_LEGAL_PERSON_REPRESENTATIVE_PASSPORT_EU_BACK = 26
export const FILE_TYPE_LEGAL_PERSON_REPRESENTATIVE_PASSPORT_EU_FRONT = 27

export const FILE_TYPE_LEGAL_PERSON_HOLDER_1_DNI_BACK = 30
export const FILE_TYPE_LEGAL_PERSON_HOLDER_1_DNI_FRONT = 31
export const FILE_TYPE_LEGAL_PERSON_HOLDER_1_DRIVE_LICENSE_BACK = 32
export const FILE_TYPE_LEGAL_PERSON_HOLDER_1_DRIVE_LICENSE_FRONT = 33
export const FILE_TYPE_LEGAL_PERSON_HOLDER_1_RESIDENCE_CARD_BACK = 34
export const FILE_TYPE_LEGAL_PERSON_HOLDER_1_RESIDENCE_CARD_FRONT = 35
export const FILE_TYPE_LEGAL_PERSON_HOLDER_1_PASSPORT_EU_BACK = 36
export const FILE_TYPE_LEGAL_PERSON_HOLDER_1_PASSPORT_EU_FRONT = 37

export const FILE_TYPE_LEGAL_PERSON_HOLDER_2_DNI_BACK = 40
export const FILE_TYPE_LEGAL_PERSON_HOLDER_2_DNI_FRONT = 41
export const FILE_TYPE_LEGAL_PERSON_HOLDER_2_DRIVE_LICENSE_BACK = 42
export const FILE_TYPE_LEGAL_PERSON_HOLDER_2_DRIVE_LICENSE_FRONT = 43
export const FILE_TYPE_LEGAL_PERSON_HOLDER_2_RESIDENCE_CARD_BACK = 44
export const FILE_TYPE_LEGAL_PERSON_HOLDER_2_RESIDENCE_CARD_FRONT = 45
export const FILE_TYPE_LEGAL_PERSON_HOLDER_2_PASSPORT_EU_BACK = 46
export const FILE_TYPE_LEGAL_PERSON_HOLDER_2_PASSPORT_EU_FRONT = 47

export const FILE_TYPE_LEGAL_PERSON_HOLDER_3_DNI_BACK = 50
export const FILE_TYPE_LEGAL_PERSON_HOLDER_3_DNI_FRONT = 51
export const FILE_TYPE_LEGAL_PERSON_HOLDER_3_DRIVE_LICENSE_BACK = 52
export const FILE_TYPE_LEGAL_PERSON_HOLDER_3_DRIVE_LICENSE_FRONT = 53
export const FILE_TYPE_LEGAL_PERSON_HOLDER_3_RESIDENCE_CARD_BACK = 54
export const FILE_TYPE_LEGAL_PERSON_HOLDER_3_RESIDENCE_CARD_FRONT = 55
export const FILE_TYPE_LEGAL_PERSON_HOLDER_3_PASSPORT_EU_BACK = 56
export const FILE_TYPE_LEGAL_PERSON_HOLDER_3_PASSPORT_EU_FRONT = 57
export const FILE_TYPE_CERTIFICATE_OF_INCORPORATION = 58
export const FILE_TYPE_ARTICLES_OF_ASSOCIATION = 59
export const FILE_TYPE_DEEPS_OF_INCORPORATION = 60




export const DEPLOY_STATUS_PENDING = 0
export const DEPLOY_STATUS_MARK_DEPLOYED = 1
export const DEPLOY_STATUS_DEPLOYED = 2


